### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by biosbeta** [Kamalnl92/Self-Supervised-Learning-for-pushing-and-grasping#2]
Very nice work! I've been trying to reproduce your algorithm on an actual robotic arm.But I don't know how to adjust heightmap_resolution since the camera I used is not SR 300.Could you please tell me how to adjust this parameter？The camera I am using is orbbec Femto Mega，1280x720 resolution（This is the default minimum resolution）

**Comment by wyl1253** [comment]
Hi Biosbeta,

Regarding the camera configuration, since we convert raw RGBD data to heightmaps, it's essential to configure parameters like the field of view (FOV) and other camera settings appropriately. I cannot provide you with a direct file for the top-down conversion. To set it up correctly, I need more information, such as the FOV and the exact pose of your camera.

If you're planning to set this up with a real robot, you can refer to Andy Zeng's work, which offers a publicly available configuration for real robots. Just keep in mind that you’ll still need to determine the camera pose and parameters for accurate results.

Best of luck!

Best regards,  
Yongliang
